FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

RUN npm install --save-dev \
    jest@30.2.0 \
    jest-environment-jsdom \
    babel-jest \
    @babel/preset-env \
    @babel/preset-react \
    @testing-library/react \
    @testing-library/jest-dom \
    @testing-library/user-event

COPY . .

ENV CI=true
ENV PATH=/app/node_modules/.bin:$PATH

CMD ["npx", "jest", "--watch=false"]
